<?php

include_once '../resources/fpdf/fpdf.php';

function create_booking_pdf(): FPDF
{
    $pdf = new FPDF();
    $pdf->AddPage();

    // Add a title
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(40, 10, 'Booking 682629');

    // Add a line break
    $pdf->Ln(10);

    // Content
    $pdf->SetFont('Arial', '', 12);
    $pdf->MultiCell(0, 10, 'This is a simple PDF generated by FPDF in a PHP API. You can easily customize this PDF with dynamic content.');

    // Send the generated PDF to the browser as a download
    // Set the content type to PDF
    header('Content-Type: application/pdf');

    // Force the file to download with a specific name
    header('Content-Disposition: attachment; filename="generated_document.pdf"');

    // Output the PDF to the browser
    // $pdf->Output();

    return $pdf;
}